package octii.dev.taxi.models

enum class MessageType {
    CHAT, JOIN, LEAVE, AUTHORIZATION, TOKEN_AUTHORIZATION, ORDER,
    ORDER_REQUEST, ORDER_ACCEPT, ORDER_REJECT, ORDER_FINISHED, NO_ORDERS, COORDINATES_UPDATE
}